### ISSUE TITLE
Compile the lucille with Visual Studio

### ISSUE THREAD

**Issue by Hao-HUST** [syoyo/lucille#1]
Hi, 

Thanks for sharing your work.

I noticed that the lucille can be run on Windows, is that the corresponding sln project on VS is available or can you give me some suggestion on how to make the sln project file for lucille？

Thanks again.

**Comment by syoyo** [comment]
`lucille` is not maintained anymore.

You can take a look at https://github.com/mmp/pbrt-v3 , appleseed renderer https://appleseedhq.net/ or other OSS renderer as an alternative.
